---
services:
  vscodeserver-powershell:
    image: devplops/vscodeserver-powershell
    container_name: vscodeserver-powershell
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ~/vscodeserver-powershell/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped